--require('toggleterm').setup({
--  size = 20, -- Height of the terminal window (for horizontal splits)
--  open_mapping = [[<leader>t]], -- Keybinding to toggle the terminal
--  direction = 'horizontal', -- Options: 'horizontal', 'vertical', 'tab', 'float'
--  autochdir = true, -- Automatically change the terminal's working directory
--  persist_size = false, -- Terminal size doesn't persist between toggles
--  close_on_exit = true, -- Close terminal when the process exits
--  shell = vim.o.shell, -- Use the default shell
--})
--
---- Automatically update the terminal's working directory when opening a new buffer
--vim.api.nvim_create_autocmd("BufEnter", {
--  callback = function()
--    if vim.bo.filetype ~= "toggleterm" then
--      local term = require("toggleterm.terminal").Terminal
--      local current_terminal = term.get(1) -- Get the first terminal
--      if current_terminal then
--        current_terminal:change_dir(vim.fn.expand("%:p:h")) -- Change terminal directory
--      end
--    end
--  end,
--})

